name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - main

variables:
  acrName: "guruacr.azurecr.io"
  imageName: "content-agent"
  dockerFilePath: "Dockerfile"
  buildPlatform: "linux/amd64,linux/arm64"
  trivyCache: "$(Agent.HomeDirectory)/.cache/trivy"

pool:
  vmImage: "ubuntu-latest"

steps:
# 0. (Optional) Check Docker & buildx exist
- script: |
    cat /etc/os-release
    docker version
    docker buildx version
  displayName: "Check Docker & Buildx"


# 1. Login to ACR (service connection: guru-acr)
- task: Docker@2
  displayName: "Login to ACR"
  inputs:
    command: "login"
    containerRegistry: "guru-acr"


- task: Docker@2
  displayName: "Build content-agent image (local for scan)"
  inputs:
    containerRegistry: "guru-acr"          # service connection
    repository: "$(imageName)"             # content-agent
    command: "build"
    Dockerfile: "Dockerfile"
    buildContext: "."
    tags: |
      $(Build.BuildId)

# 4. Aqua Scanner (Trivy Local Mode)
- task: Docker@2
  displayName: 'Docker login (service connection) for Aqua'
  inputs:
    containerRegistry: 'login aqua'
    command: 'login'

- task: aquasecScanner@4
  displayName: "Aqua Scan multi-arch image"
  inputs:
    image: "$(acrName)/$(imageName):$(Build.BuildId)"
    scanType: 'local'
    containerRuntime: 'docker'
    scanner: 'registry.aquasec.com/scanner:2022.4.868'
    connection: 'ocp-test'
    registry: 'guru-acr'
    register: true
    arguments: "--cache-dir $(trivyCache)"
    