name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - main

variables:
  acrName: "guruacr.azurecr.io"
  dockerFilePath: "Dockerfile"
  trivyCache: "$(Agent.HomeDirectory)/.cache/trivy"
  buildContext: '$(Build.SourcesDirectory)'
  tag: '$(Build.BuildId)'
  imageName: '$(imageRepository):$(tag)'

pool:
  vmImage: "ubuntu-latest"

steps:
- checkout: self

# 1. Login to ACR (service connection: guru-acr)
- task: Docker@2
  displayName: "Login to ACR"
  inputs:
    command: "login"
    containerRegistry: "guru-acr"


# Build image from Dockerfile
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    Dockerfile: $(dockerfilePath)
    buildContext: $(buildContext)
    tags: |
      $(tag)

# 4. Aqua Scanner (Trivy Local Mode)
- task: Docker@2
  displayName: 'Docker login (service connection) for Aqua'
  inputs:
    containerRegistry: 'login aqua'
    command: 'login'

- task: aquasecScanner@4
  displayName: "Aqua Scan multi-arch image"
  inputs:
    image: "$(acrName)/$(imageName):$(Build.BuildId)"
    scanType: 'local'
    containerRuntime: 'docker'
    scanner: 'registry.aquasec.com/scanner:2022.4.868'
    connection: 'guru-host'
    arguments: "--cache-dir $(trivyCache)"


